#6 Project - HTML Responsive Design (The Next Web Clone)
chubaquelo/The-Next-Web-Responsive-Clone pull request #1
Opened 2020-09-04 22:03 UTC by chubaquelo

In this project, I practiced my skills in responsive design using just media queries in CSS.
I did this project using flexbox, grid, and floats to align the divs and change the grid template in each screen size.

- Media queries for desktop, tablet an cellphone
- Header responsiveness using flex and float for the logo
- Sections made using grid layout
- Footer using flexbox

2020-09-05 00:56 UTC, Spayco requested changes
# Changes Requested 

Hello! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] fix the linting issues

- [ ] The Navbar should always be on the screen even when you scroll down ([link to site](https://thenextweb.com/))

- [ ] all the big images are not taking the full width on all screens, do not specify an exact pixel number, instead make it responsive

example: 
![image](https://user-images.githubusercontent.com/11758151/92293007-1e032e80-ef18-11ea-83dc-db8fcf7de3d8.png)


- [ ] The **Latest Funding Round** cards should change from 4 to 3 on medium and small screens

- [ ] on medium screens The 3 small titles next to **Latest Funding Round** should become under it in one line, yours is on top of it

**Yours vs. Original** 

![image](https://user-images.githubusercontent.com/11758151/92293134-fa8cb380-ef18-11ea-8665-19efffddfc7d.png)

- [ ] on small screens the small titles next to **Latest Funding Round** should be under it, each link on its own line

**Yours vs. Original**

![image](https://user-images.githubusercontent.com/11758151/92293248-f319da00-ef19-11ea-887a-d82ecac3a20a.png)


- [ ] the big 3 images and latest news section merge on medium screens

![image](https://user-images.githubusercontent.com/11758151/92293176-42133f80-ef19-11ea-82cf-4d4e6716aad8.png)


- [ ] The Categories Section should be 2 rows on medium screens 

**Yours Vs. Original**

![image](https://user-images.githubusercontent.com/11758151/92293203-86064480-ef19-11ea-9496-b65f9830c65c.png)


- [ ] You have a horizontal overflow on specific widths

![image](https://user-images.githubusercontent.com/11758151/92293357-de8a1180-ef1a-11ea-9cd8-9f70c9022dcf.png)

![image](https://user-images.githubusercontent.com/11758151/92293366-f06bb480-ef1a-11ea-9036-9cb4be762062.png)

![image](https://user-images.githubusercontent.com/11758151/92293378-05484800-ef1b-11ea-9f45-a20c3b137130.png)

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-09-05 00:56 UTC, Spayco commented on css/style.css
> +  } */
- [ ] Remove Commented Code ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-09-05 00:56 UTC, Spayco commented on index.html
> +    <meta name="viewport" content="initial-scale=1.0" />
- [ ] Fix the linting error `The 'viewport' meta element 'content' attribute value should contain 'width=device-width'.`

add `width=device-width` to the content attribute.

2020-09-07 20:04 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️


#### Hey @chubaquelo, its always nice to review your projects! I must say that overall the project looks really nice and I can see that you made some required changes, and don't worry, you're almost done, there are just some required changes that you have to implement in order to get approved, and also add a nice project to your portfolio:


_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.

## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
### Large screens issues:
- [ ] Add a gap between those articles (Check image below)
- [ ] Add the TNW logo at your footer (Check image below)
### Yours
![image](https://user-images.githubusercontent.com/56762529/92413940-9fc9a680-f128-11ea-809a-9149079aa25a.png)
### Original
![image](https://user-images.githubusercontent.com/56762529/92413949-ab1cd200-f128-11ea-8a1c-4e2883395abc.png)

### Medium screen issues
- [ ] Those images should fill the whole width of its content (So the text will remain below the image, not beside). Latest deals is also facing the same issue.(Check image below)
#### Yours
![image](https://user-images.githubusercontent.com/56762529/92414028-e9b28c80-f128-11ea-9fd0-f7abc546f08a.png)
#### Original
![image](https://user-images.githubusercontent.com/56762529/92413640-67759880-f127-11ea-929e-4671001e7ec8.png)

- [ ] Your latest section with the class `.cat-last-art-latest` (selected⤵) should end at the same place that that image above it. (Check image below)
#### Yours
![image](https://user-images.githubusercontent.com/56762529/92414094-1bc3ee80-f129-11ea-9afb-542077f58a3b.png)
#### Original
![image](https://user-images.githubusercontent.com/56762529/92413688-94c24680-f127-11ea-8f68-21339654b599.png)

### Small screen issues
- [ ] There are too much margin at the x-axis, it would be better if you decrease it. (Check image below)
#### Yours
![image](https://user-images.githubusercontent.com/56762529/92413728-c9ce9900-f127-11ea-84d4-ef6fa8309ef4.png)
#### Original
![image](https://user-images.githubusercontent.com/56762529/92413734-d0f5a700-f127-11ea-8c73-7dd2a72b8f52.png)

- [ ] Your footer is breaking (all items should stay in the same line) at small screens, kindly fix that. (Check the image below)
- [ ] You have a blank space at the end of your page on small screens. Please get rid of that. (Check the image below)
#### Yours
![image](https://user-images.githubusercontent.com/56762529/92413755-ecf94880-f127-11ea-8d07-5eec676c735e.png)
#### Original
![image](https://user-images.githubusercontent.com/56762529/92413758-f5518380-f127-11ea-902a-a081b5918530.png)


## [OPTIONAL CHANGES]
**⚠These are mandatory changes, but since It wasn't pointed out earlier, I'll mark them as [OPTIONAL]:**
#### Good practices (Those changes to make you code like a pro 👽)⤵
- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/92414712-dbb23b00-f12b-11ea-8e6d-3378c4085eaf.png)

### Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question about this review? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-09-08 00:50 UTC, kevincappuccino approved these changes
# [STATUS] PROJECT APPROVED 🍾

## Congratulations @chubaquelo! Good job making my previously requested changes, you have also followed the best practices throughout the code, you guys got my attention and have my approval to move on!_ 🥇💯

### It was a pleasure to review your code
<img src="https://media3.giphy.com/media/fWfowxJtHySJ0SGCgN/giphy.gif">

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-09-08 01:01 UTC, merged